### ISSUE TITLE
Link dump

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-json-schema#6]
https://www.tbray.org/ongoing/When/201x/2019/12/02/Strongly-Typed-Events

> I was sort of gloomy and negative about the notion of automated mapping between messages on the wire and strongly-typed programming data structures. Since we just launched a Schema Registry, and it’s got my fingerprints on it, I guess I must have changed my mind.

> Writing code to map back and forth between bits-on-the-wire and program data structures is a very bad use of developer time.

> ...most messages are in JSON, and I have repeatedly griped about the opacity and complexity of JSON Schema. So, why am I happy about the launch of a Schema Registry? Because it lets us do two useful things: Search and autocomplete. 

> Let’s talk about Autocomplete first. When I’m calling an API, I don’t have to remember the names of the events or their arguments, because my IDE does that for me. As of now, this is true for events as well; the IDE knows the names and types of the fields or sub-fields. This alone makes a schema registry useful.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-json-schema/-/issues/6.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
